[theme]
# Main colors
primaryColor = "#FFC107"  # Vibrant yellow for primary actions
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#E0F2F1"  # Soft mint green for content areas

# Text colors
textColor = "#37474F"  # Dark charcoal for main text
font = "Roboto, 'Helvetica Neue', sans-serif"  # Clean, sans-serif font similar to the image

# Additional custom colors (for use in your CSS)
[theme.colors]
fractalBlue = "#4285F4"  # Approximation of the blue dot in the logo
fractalRed = "#EA4335"   # Approximation of the red dot in the logo